/* XPM */
static char * C:\Users\debor\Documents\GitHub\LCOM_WizardsChess\Assets _ Pieces\WhiteHorse_xpm[] = {
"71 71 65 1",
" 	c None",
".	c #000100",
"+	c #010400",
"@	c #030602",
"#	c #070A05",
"$	c #090C08",
"%	c #0C0F0B",
"&	c #10120F",
"*	c #121411",
"=	c #151715",
"-	c #1A1B19",
";	c #1E1F1D",
">	c #20221F",
",	c #262826",
"'	c #2B2D2A",
")	c #2E302D",
"!	c #303230",
"~	c #363835",
"{	c #383A37",
"]	c #3B3D3B",
"^	c #40423F",
"/	c #494B48",
"(	c #4D4F4C",
"_	c #50524F",
":	c #555755",
"<	c #5A5C59",
"[	c #5D5F5D",
"}	c #656764",
"|	c #6A6C69",
"1	c #6D6F6C",
"2	c #747673",
"3	c #787B78",
"4	c #7D7F7C",
"5	c #80827F",
"6	c #868885",
"7	c #898B88",
"8	c #8D8F8C",
"9	c #90928F",
"0	c #949693",
"a	c #979996",
"b	c #9A9D99",
"c	c #9DA09D",
"d	c #A2A5A1",
"e	c #A7AAA6",
"f	c #ABADAA",
"g	c #AEB1AD",
"h	c #B3B5B2",
"i	c #BABCB9",
"j	c #BDC0BC",
"k	c #C3C5C2",
"l	c #C7C9C6",
"m	c #CDCFCC",
"n	c #D0D2CF",
"o	c #D3D6D2",
"p	c #D8DAD7",
"q	c #DEE0DD",
"r	c #E2E4E1",
"s	c #E5E8E5",
"t	c #E9ECE8",
"u	c #EEF1ED",
"v	c #F1F3F0",
"w	c #F3F6F2",
"x	c #F9FCF8",
"y	c #FBFDFA",
"z	c #FDFFFC",
"                                                                       ",
"                  ++            ++++                                   ",
"                 +++++         +++++                                   ",
"                +++++++       +++++++                                  ",
"                +++++++      +++$q+++                                  ",
"                +++:{+++    +++,qr*++                                  ",
"                +++1t++++   +++gzv^++                                  ",
"                +++}xn*+++++++/zzz1+++++                               ",
"                 ++-sx(+++++++uzzz1++++++++++                          ",
"                 +++lzz;;;;;;8zzzz7;=#+++++++++                        ",
"                 +++qzzzzzzzzzzzzzzzpe443'++++++++                     ",
"                 +++qzzzzzzzzzzzzzzzzzzzzwuo>+++++++                   ",
"                +++}xzzzzzzzzzzzzzzzzzzzzzzzzz|]+++++                  ",
"               +++#nzzzzzzzzzzzzzzzzzzzzzzzzzzzuh{+++++                ",
"               +++'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz8&++++               ",
"              +++_zzqewzzzzzzzzzzzzzzzzzzzzzzzzzzzzm[++++              ",
"             +++=jz0$@'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzxh++++             ",
"            ++++9z0++++tzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz9++++            ",
"            +++bzr+++++vzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzh++++           ",
"           +++-px<+++++zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz0++++          ",
"           +++0zo;++++|zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzb+++          ",
"          ++++zzj++++#izzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz3+++         ",
"          +++szzj++++6zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzn>+++        ",
"         +++5zzzv(++hzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzl+++        ",
"         ++%izzzzzerzzzzzzzzzzzzzzzzzzm++izzzzzzzzzzzzzzzzzz,+++       ",
"        +++|zzzzzzzzzzzzzzzzzzzzzzzzzzm++[zzzzzzzzzzzzzzzzzzr&++       ",
"       ++++zzzzzzzzzzzzzzzzzzzzzzzzzzzg++[zzzzzzzzzzzzzzzzzzz5+++      ",
"       +++fzzzzzzzzzzzzzzzzzzzzzzzzzzz-++2zzzzzzzzzzzzzzzzzzzl#++      ",
"      +++/wzzzzzzzzzzzzzzzzzzzzzzzzzzk+++tzzzzzzzzzzzzzzzzzzzz;+++     ",
"      +++6zzzzzzzzzzzzzzzzzzzzzzzzzzt)++{zzzzzzzzzzzzzzzzzzzzzz+++     ",
"     ++++zzzzzzzzzzzzzzzzzzzzzzzzzzz8+++wzzzzzzzzzzzzzzzzzzzzzz^++     ",
"     +++zzzzzzzzzzzzzzzzzzzzzzzzzzzu+++#zzzzzzzzzzzzzzzzzzzzzzzf+++    ",
"    +++(zzzzzzzzzzzzzzzzzzzzzzzzzzj#++++zzzzzzzzzzzzzzzzzzzzzzzl*++    ",
"    ++#fzzzzzzzzzzzzzzzzzzzzzzzzzr$+++++zzzzzzzzzzzzzzzzzzzzzzzx]++    ",
"   +++)zzzzzzzzzzzzzzzzzzzzzzzzzm++++++$zzzzzzzzzzzzzzzzzzzzzzzz<+++   ",
"   +++mzzzzzzzzzzzzzzzzzzzzzzzzl*++++++;zzzzzzzzzzzzzzzzzzzzzzzzr+++   ",
"  +++~zzzzzzzzzzzzzzzzzzzzzzzzr++++  ++~zzzzzzzzzzzzzzzzzzzzzzzzz+++   ",
"  +++jzzzzzzzzzzzzzzzzzzzzzzxg#+++   ++1zzzzzzzzzzzzzzzzzzzzzzzzz_+++  ",
"  ++/xzo[uzzzzzzzzzzzzzzzzzz[@+++   +++8zzzzzzzzzzzzzzzzzzzzzzzzzp+++  ",
" +++1za+++dzzzzzzzzzzzzzzzs~++++    +++8zzzzzzzzzzzzzzzzzzzzzzzzzq+++  ",
" +++tz++++&zzzzzzzzzzzzzzf'++++     ++$fzzzzzzzzzzzzzzzzzzzzzzzzzs-++  ",
" +++zz+++++zzzzzzzzzzzzx1+++++      ++'xzzzzzzzzzzzzzzzzzzzzzzzzzx<++  ",
" +++zz4+++4zzzzzzzzzzzf<++++       +++)zzzzzzzzzzzzzzzzzzzzzzzzzzz1+++ ",
" +++zzy6+cxzzzzzzzzzzk@++++        +++ozzzzzzzzzzzzzzzzzzzzzzzzzzz1+++ ",
" +++zzzzzzzvhpzzzzzr3+++++        +++-zzzzzzzzzzzzzzzzzzzzzzzzzzzz8+++ ",
" +++zzzzzzs~$,9zzzw/++++          +++dzzzzzzzzzzzzzzzzzzzzzzzzzzzzl#++ ",
" +++lzzzzz)+++&ozx_++++          +++'pzzzzzzzzzzzzzzzzzzzzzzzzzzzzz%++ ",
" +++(zzzzz)+++&oza++++           +++bzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz%++ ",
"  +++jzzzz)+++1zj++++           ++++zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz%++ ",
"  ++++#_:>++++do++++           +++)wzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz%+++",
"   +++++++++++p!+++           +++#gzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz{+++",
"    ++++++++++++++           ++++[zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzc+++",
"           ++++++           ++++2zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzl+++",
"           +++++           ++++(zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzt+++",
"                          ++++}zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                         ++++}xzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                        ++++:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                       ++++|zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                       +++<zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                      +++/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                      +++pzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                     +++7zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                     ++$rzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                    +++>zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                    +++tzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                    +++zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                    ++'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                    ++:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++",
"                    +++++++++++++++++++++++++++++++++++++++++++++++++++",
"                    +++++++++++++++++++++++++++++++++++++++++++++++++++",
"                    +++++++++++++++++++++++++++++++++++++++++++++++++++"};
