#pragma once

/* XPM */
static xpm_row_t const hufflepuff_logo[] = {
"120 146 65 1",
" 	c None",
".	c #000200",
"+	c #080B04",
"@	c #10110C",
"#	c #141200",
"$	c #1B1A12",
"%	c #201C03",
"&	c #1A1C1A",
"*	c #262725",
"=	c #2B281A",
"-	c #322B0A",
";	c #373002",
">	c #3E3601",
",	c #383525",
"'	c #353633",
")	c #4D4306",
"!	c #424340",
"~	c #484330",
"{	c #524A27",
"]	c #5B500E",
"^	c #56523C",
"/	c #625601",
"(	c #555653",
"_	c #5A5C5A",
":	c #706102",
"<	c #67624C",
"[	c #73661A",
"}	c #656663",
"|	c #74672E",
"1	c #716946",
"2	c #807009",
"3	c #70716D",
"4	c #7C7E7B",
"5	c #94830F",
"6	c #838582",
"7	c #8C8563",
"8	c #978640",
"9	c #948A5B",
"0	c #A69201",
"a	c #8E908D",
"b	c #B8A20F",
"c	c #B5A13C",
"d	c #A1A39F",
"e	c #AAA580",
"f	c #B9A65C",
"g	c #C4AC00",
"h	c #B2AB79",
"i	c #AEB0AD",
"j	c #D4BA06",
"k	c #E4C800",
"l	c #DBC467",
"m	c #E5CD24",
"n	c #D5CF94",
"o	c #E8D04B",
"p	c #F1D400",
"q	c #DFD082",
"r	c #CFCFCC",
"s	c #ECD264",
"t	c #F3D672",
"u	c #EFD77B",
"v	c #E3E4E0",
"w	c #EFE6A5",
"x	c #F8EB9F",
"y	c #FAF2B0",
"z	c #F7F9F6",
"                                                                                                                        ",
"                                                            +++                                                         ",
"                                                           +'3@@                                                        ",
"                                                         -+(4}}@#                                                       ",
"                                                        -@_43___+.                                                      ",
"                                                >)>;%%#@*343_(((}@.         >                                           ",
"                                             .;(!!(}444643}('*!'_}*++    >#..%                                          ",
"                                             ..44444443}_((!!6a!(__(*++@.+@..-                                          ",
"                                             ..'43(((((('*!!aii6_'**(}33__}*@)                                          ",
"                                              ..43____''3adiiiiida66*(_((((.!^'%                                        ",
"                                    -%   !((((*+33___*}aiiiiiiiiiiia3'____'!}}_('**-:                                   ",
"                                $'((({{='___34_.34__'}aiidiiiiiiiiid4'__(}*66a}_____!''=                                ",
"                            #$'(___3}_______a6d*(4_(!6diiiiidiiiiiid4'___((444a}(____((_&!&*                            ",
"                         %'((_____}a6a3___3a444!&4_!_6didadiiiidddid4'__}*3444464__}4666(!__(!'@                        ",
"                       *'(_______(66446aaa64444}.3}((6da}}66dda6646d6'_(}'44444446666444a______(!*$,                    ",
"                    ;- '_(((___((3a444644666444a@!4_*46'!!*}4a4'''*36'__'(4644aaaaa4444466_((_____(!'$                  ",
"                   =!(!(_6663336aa4446iaa433aaa6*&4}('}!__('34*(__(*!!(_*__6a6}__}3a44446aa444444____a3$                ",
"                  @(a(___d466a6aaaaaard3___((}}_~@_4_!'*(__(*'(____!!__!!___}______}a4aiida6466666(__3ra                ",
"                   +ad(_664446dd3}}ada}____((!(!]-'4__(!______}_____(__*!*@*(_______}add4336a4444a____d&                ",
"                   -@ii_d444aia}____^,,=-@@+..:0jb@}4}_(!'***@*''!(}}}<=|%+))>~'!!(_________}a444a4_('*+                ",
"                    &*3d4446i4__(!~>:50gj/....+jkk;*,);.@@+..-m-05[)]]]:p-;kkkkgb2)-*'(_______66446_*!*                 ",
"                    @(''}4aa3_('@.)jjkkkkj.....%jkgjkkj-.....%p)0pkkkkkkp)2pkkkkkkkjb]$'!(_____664!!4(+                 ",
"                    &!33''_((,%....2kkkkkk/.....-jkkkkkg....+%pppkkkkkkkkkkkkkkkkkkkk.#b|,'!(___3'}44')                 ",
"                    &!344(&,%2%....%0kkkkkj....../kkkkkk]...+%pkkkkk0jkkkkkkkkk2pkkkb%)kkkb/,'(_!(a44@                  ",
"                    &_}64a_-|j2.....;jkkkkk2......:kkkkkg+...%pkkkkg-0kkkkkkkkk-kkkkkppkkkkkj]'__}646@                  ",
"                    *__a4a(^;kj%.....2kkkkkk+......5kkkkk:..+%pkkkj--%>jkkkkkk5#5kkkkkkkkkkkk[!__}646$b                 ",
"                    !__a4a(_-jk5.....+bkkkkk0.......gkkkkk;..%j)pk)/#j;gg0kkk0#%/jkkkkkkkkkkk[!__4644'|                 ",
"                    33a64a(_;jkk%.@...;kkkkkk#...%@.#jkkkkb+.%p0pk)j-0kk/)jk0%.5+#kkkkkkpb-kk]!__44443$                 ",
"                   '444463__;gkk5.+....:kkkkkk+%)5g%.;kkkkk>.%pkkkp/#-0kkkkk:2]20>kk2kkkb#.gp]!__44444(                 ",
"                   !idi4a___-jkkk>......5kkkkkg5k#h0..:kkkk0.%pkkkkp-;kkkkkkpk-:pkkk.bpg%b.-k]!___4646_@                ",
"                  *_i6d46a(_-mkkkg.....++jkkkkkk-'vb]..:kkkk%%pkkkkk)gkkkkkkp5.#>pkpppk0b]+:k/~____44a_('               ",
"                =*__a4444a}({mkkkk>.....+>kkkkk5@'zag-..5kkkj%pkkkkkkkkkkkkkkj.-pkkkkkkkp>)pk[,____346a}&&              ",
"             &'!(__3a444a4_(/mkkkkj-......2kkkg@+*vr|g+..0kkj%pkpkkkkkkkkkkkkp2bkkkkkkkkj#%kk5,___(64446a_'*=           ",
"            (i6__(36444a}__@/gkkkkkb......#kpg-++$}da0:..#jkj%pg2pkkkkkkkkkkkppkkkkkkkkkj@)kk0-(___a444446_ai@          ",
"            $}drd64444a}__*>-@/jkkkk0.....05%%++++&$i9g#..;kj%p5/pkkkkkpg:kkkkkkkkkkkkkkpgkkkm-1___aa644a}4i3*%         ",
"            -!*!a644463__*.0-@(#0kkjk].##5]++@++++@@'rj:...)j%p]%gkkkkkp2-mkkkkkkkk0jkkkkkkkkk5><____}a4aa3'!}*         ",
"             ~_(''344a__').j;$zr,)jkkj2/g-+%aa'+++++@$/j+...:%/%%%p2bkk0-.%gkkkkkkj@kkkkkkkkkjk2;____(6a('(__6$         ",
"             -(__}'}4a(!{j#0;&zvva%:jgb5%@+*rzz7$++++@@b2....%:5.)k2/kb/5@;5kggkkkg%:kkkkkkkk>jk2=___6!(4___(!          ",
"             %{__}4!(}(*jk0#-$zrrza+$@+++++++(rzr~$$+++$0/...%p-.gkppkjpb@bkj#)pj])#-;kk:jkkk%jpk5*(_!}a6___}%          ",
"              -~(444__({mkkj/'zr6_r_&@.*da($.+@3vvzv=++!=b%..%p-.bkkkkkp5#gkkbmkj>j##bkk+bk55]%2kj1!_(_a6___(           ",
"              -$}a446}_%mkkkb@v34dvzvvrvvvvr4$++'vzzd@$va]2..%pg]pkkkkkpg-pkkkkkkkk%#pkkgkk0p/]0km8!__36a___*           ",
"               %a44446_=jkkkk/3rvzzzzivzvvvzvv3@+rdvz3*(}=b#.%pkkkkkkkkkpjkkkkkkkkk)%pkkkkkkb#)kkm[(__a444__$           ",
"              -(a444443(>kkkkk>dzzzzz}!zzvzzzzzr!@.*vz}*z42:.%pkkkkkkkkkkkkkkkkkkkj>jkkkkkkkj;0kkm{__}6446((,           ",
"              ,}a444443_)kkkkk2+3zzzz*+4zzzzzv4(d=++,zz~4@-5.%pkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkjkkkj-__}a44i(!            ",
"              %(a444444_-jkkkp-+'vzzr++$vzzzr'di*=+++6zi$&a>);jkkkkk5jkkkkkkkjjkkkkkkkkkkkkkkkkkkj=___64i4(!            ",
"               '6644443_=bkkkk;!zzzv'+++3zzz'zzzz'++++dzr'43:{^^|bkk)5pkkkkkp50kkkkkkkkkjkkkkkkkkg=___44r__*            ",
"               '}a4446}!%@gkkp]zzzv!++++'zzv(zzzv*+++++azv'($}}3(}cb%)5kkkkkp))pkkkkkkkb]pkkkkkkk0*___66i(_@            ",
"               (_}a446((+.%gkk7zzv,+++++'zzivvvd3@++++++_zr*%=***(}|+-+0g5kk:++>kkkkkkp->kkkkkkkm5'___aa4__$            ",
"               *__a446(_++.%jk7zzr@+++++*zvava}++++++++++!zv7~@***&_(005:#k0%)%%2k>2kp0%.;jkkgjkm8'__}aa(__$            ",
"               {!_a446(_=...)k:vzz3#++++*vvvv}@'+...++++++aza6$*****__!bpppgg2)jjp50kj-b%5:kp-]kk:!__446___$            ",
"               =(3a646}_!...#:k{vzr@++++'vvvvr+di$+...++++6((a3&*****_3}ckkp0+.)pkppkkk5#pmkkkkkk2!_}a4a__($            ",
"               =}a6a446(^.+..#5j;vza@+++*vrvvvr(_vzv3..+++4!'!*&******!3(1jkkg-ppkkkkkk;.5kkkkkkk[!_a4446_'             ",
"               =64a44aa(^.#...#g>rzzr@+++*rvvvvv6'rrv6...+&3*_*********3}4|kkpppkkkkkkkj-pkkkkkkm)^_a444a(.             ",
"               =46d44da__.#....-;^vzz6++++3rvvvvvi'6rr4....(&'&*********!(6|jkkkkppkkkkkjkkkkkkkb-(_444ai*              ",
"               =_a4ia66__.......>2=azr++++@irvvvvrr3'3di'$$*'''''''''''''!_4|kkkpp#0kkkkkkkkkjkm5*___64ia(@             ",
"               -(}aai4a__$.......:g%ai@@++@@rrrrrrd'$@@@@@@$**************!36ckk2%.%:kkkkocc8|~~~~^~~~~(!!,             ",
"               -(__a44a(_'........0/=$@&'@@+(rri_***''''''''''''''''''''''*!}4b0;j./]0j8{{|81989|{,==~999^={            ",
"               -(__3644_((+.......+@@*&@$&****$@&'&&****''!(!''!''''''''''*'!}|bc8~|c|~flttttttttttuqf9{,1f8,1          ",
"               {!__}663__^b#......+&*********&$@&$@&**&&*!(!!!!!!!!''''''~{<1{{18ccc|futttttttttssf|qqutlf,~91,         ",
"               )!__3646(_^bj;.....@*********&@!'**_64!''*'!!!!!!!!!!'!!19||ffttttttttutttttttttux1+.=qutttf|1~1,1       ",
"                !__aa4a__^bkk;...+********+@*6!''!''_!''''!!!!!!!!!(<<798fluuttttuuuuuuuuxxxxxxh$....^qut{.+fq~~=1      ",
"                !_3d6464_^bkkg+.+********&@'3'***''''!****'!!!!(<1<|9ffuuuuxqxxxxxxxxxxxyyyyyn~..+..+9wh=...@qu8{$      ",
"                !(6d44ia(^bkkk:.&*******&@4!*****'''!!'***,{,~|888luuuuuxxwywyyyyyyyyyyyyynny7...+=$ew1@.==..^utu9$|    ",
"                !_6a44r63^bkkkk;&*******&@*******'''!!~][[]]cgstttllluuxwywywyyyyyxxxnyyw7$,y^...$hnww$..^n+$huttt1$]   ",
"                !_3644a44]bkkkk]&*******$}@*!&*$$'*,^1[][cltlquuuqqqxxxywwhewwwwxyxyn+wy~..ew=...$heww$..<x~nwxtttu7$)  ",
"                !_643(''&$)5gkk-********,i@*v.+i*$$8|[bstsssqnqxqwyyyywwyh$79~1wwyw9.+w7+.=ww@...++~wy~..1wwwxyxtttu9%2 ",
"                !43'&&******$>:&********~d$}3-^3%~18ll~{fqxw^ewyywyyyyyyw,+&..@9h$@..1w$..^wn+....+1ww@..^111hwwutttl<> ",
"                !!&***********&&&*****'*!}*3]j=~8qusc%@*~nn~=wwyyywyyyyy^.+&@..=w=...^y~..^n$...@1nwwn@..+=,@.~nxutttf= ",
"               =&***************&&***&**&-5][^fuqwwn$.**en=.=wywyywwwwn1..@7h...h9...,wh..^9+...$nwyn$...hxyw@.1wuttsu| ",
"              @@@*@&*$*$*$$***********'[5:~8uuqn9nn$.,7~w^..,wywyyhnwy7@..@en+..7w+..^wh..~nw,...1wy7@^+.nww~@.1wutttl1 ",
"             -@a(@3_$(r${i'*********]22{8tuuuu1..*1..<yn<'&.~wwyw@.+hww7&&+en+..1w<..9wh..~wy1...<wywy,..nwyn@.hxttttf  ",
"     ~>]     $3r,~r~,r(f3i%-=***,*]b|8sttussn=...1*..^wn77..1wwy^.+&*<wh&&.7n+..~y1..ewh..7wyn...^yyyn...hwxy,9wxtttt1  ",
"    )oooc8{{|[ehmeem0ejgr|c{;,^0b08cstttstxy$..$,n&..^hnw1..7wwh'*'***nn*&+7h...,x,..9wh..9wy^...^xyyn...hyxxwwxutttt   ",
"     gmmmmkkkmfomlomjommejosoj-88stttttuxxxh...n<w*..$@nww@+7wn'*'e***nh*&+e9...,w=..$y~..1hw,...~yyyn...hyyxxxxttttt   ",
"     cmoooooooostuulssosuu~lsp{sttttuuxxxxy,...w=w~...+nww'*ewe**'y!*&nh*&+h^...^w+...$...+~w,...~xyyn...wyyyyxxttttt   ",
"     {koxxxuuuuqh^quxqxx9=9qop]sttttxxxxyyy,..++$w^.@&<wyw'*ewe**'<**ewe&&+*...+hw....+,+.=nx<...,xyyy...wyyyyxxtttt    ",
"      jmxxqqqwx1=hxxw9^@..nwmj|stttuxxxyyyn=....+n$@&'wyyn**ey7**'*7nwye&&@&...=wwh$@^hw^1wwy7...~yyyw...wwyyyxutttl    ",
"      [muxxxwe=.,wyn$.....nwyj[mstuxxyyyw^^@...~hh@@&<wyyn**ey7***wwwyye&@+enh7nwywhnwwwwwwyye...^yyyn...wwyyyxutttf    ",
"     -2mm1<<,...7wyn......xwyo[motxxwyyw^+e...@ww7@@&7yyyn**ewe**&wwnwwe&@=wwwwwyyyywwyyyyyyyh...1wyyn...nwyyxxutttf    ",
"     {jmm2......ewyyn$....xwyo>mouxwnw7=.$~@..$wwy7@&hwyyn**7we&*&ww~'nh&@~wwyyyyyyyyyyyyynny1...eww~7...nyyxxxttttf    ",
"     -bmmm2.....hwyyy1....wwxo)joqn^9h$..=1$..=wwy7@'wwyyn*&7we&&@w7&*nh&@~wwyyyyyyyyyyyyyh$~....hwn..+.+wyxxxxttts|    ",
"     +pmmmm~...+nwyyy1....ywxo]j2,$.9w1..=y1..=wwy1@&ewwwh@@7wh&&.7@.7w7@@=wwwwyyyyyyyyyyyy^...+{nxx^.@^hwxxxxxtttt|    ",
"     /mmmmmh...+nwyyy<....xwxo]j-...7w9..=y7..=wwy1@@7wwy7@@<ww'&&..=ny7&@@<nnwwyxxxxxxyyxxu1{9qqqutl{qxxxxxxxxtttt|    ",
"     5mmmmmc....7wyyy^....xxxo]j5...<x<..~y1..,wwy<@&7wyy~&&*eyw'*&$nwyh@@$&+^wxxxutuuxxxtttuuuuttttttuttuxxxxxtttt|    ",
"     :mmmmm5....7wyyy@....xxxo>jo=..~x^..<w$..~wwy~+@7wyn&~hh7nww7nnwyye&<nehxxutttttttllutlf||8||1||8fflttuuxxtttt]    ",
"     -gbjmm0....ewyyy~....xxxo)bo~..,x^..1w,..~wwy,+.hwy<~nwwwwwyywwyyy~*nwwqutlootttuq9=97=;[[=**''!!==~|lttttsstt|    ",
"     ...+->-....1nyyye....xxxs5)o~..$w1..<w,..~wyy,+.hnw^hnwwwwwwwwwwwh=hqxuutt~8lqqqq1=@~:0pkj,__6444($] {|ltttsts8    ",
"    ..+;)-%#......=7nh...+xxxlb/o=..@w7..$n~..,wyw=@@ewyyyyyyyyyyxxyxq,hxuults|&@~^<~&',+..5pkg=__3446}*]   %{futtoc]   ",
"   .. >pmpm0....~~+..+....xxxl]bo=...7$...e~..~wyn++.9wwwwwwwquuullll$fusllf|=&**&+@@*_!+...5pj,__}646_($    1={lsmm]   ",
"  ... >mmmm0....7yw9~$....wxwu;mo$.......$n$..~wy1.@.ewyxxxuuttttustfclf1~*&**********'_@...+5k,__(446__$   |9q[=foo|   ",
" ...  -p)om0....7wyyyn....$9qu)ms=....~=.en...<ww,@&^nwqquuuuuulusl91~&.&*'''**********!@+...#j,____a44_&g  |7lm[-om|:  ",
" ...  %m#so5....7wyyyn....~~hl]msl~.~hn$1wn...nw^++1wwuuulutsssc^=@&*****&***************.....>;____a4a(!5  |1lmm-{of   ",
"  .   +;#sm5....7wyyyh....wxql[mtux<wwn1ww,..7ww@hxwutuusc899~.&&********+&************.,+....+%____a4a_()  ||mmk[^9f   ",
"  ... ..#so5+..+7wyyyh....wwxf[mtuxxxywww^@.~wnwwqulsollb~'(aa}@****''''**!&'''**''''**@.>....+#(__a4463_>  >8jcc9^,9   ",
"  .....[lsmp;..+7wyyyy1...nxxc2msqxxxyyn,=7nxwyuuutoc{|~_diiirri&**'*****!aa!*'*''*****@.5+....#(_}a444a(%  -1,$)-^,~   ",
"      #ssom5+...9wyyyh$...nxql[osuxxxxxnnwxxxttstl8{~**}iiiiidvvv!@&*****&air!*********&.0b+.+&%((34444a_#  {=b{ct{1#   ",
"      -ommm2....ewxyyn....nwqs[ottuuutuxuutttso8{~~'**@6iiiiiarrrrri*****&}drd&*********.bp0$@*$(__a6446_$  =fo2=2=9%   ",
"     .jmmmmc....7wyyyn....,wwo:otttttttttsooc{{)******@&!iaddiivvrrrr(&****6rr6@********.gk/@**&!___64a(_*   qoj8589%   ",
"     .pmmmmn....<wwyyn....@wwo:ottttttssoc5{-%b:@*******!ii34i4arrvvvv_****+44i*@***@***.j2@***&,___44a(_&   9okmsq7    ",
"     .pmmmmh....~9hwyn.....7ws:ottttooo5|[[52.k0@********diiaia3arrvvvr!***&..@@&***@***.g@*****=___366(_$    {5gt9,    ",
"     .5mmmm9.....$nwye..,^enwo[oossoc[[5jkbk:#0b@**&@****!iidiiia4aivvr3&***&*******@***-%&*****=___}64__@      ~~      ",
"      >mmmo1..=1nwwwy=~hwwwwwm[ooos[5gjkkkpb/+0k+*&3*******_aiddiiiiivva&***********@***@@*****&$___}64__*              ",
"     -2mmmc$^nwwwwww~9wwwyyysj|]:[[/0kkkkkkpg0pp)**''******&&*aiaiii4ivd@***********@***+******.$___46a(_&              ",
"      [mm0=hwwwyxyx91wwyyyyxmj]bjjk0jkkkkkkppppkj%**'*********@4a}3idaiia**************@******@.=___a464_&0             ",
"      #bmcqxxxyyyxxxxyyyyyqlmc5kkkkkkkkkkkkkkpkkk[&'!*@@*******@&!366aaadi!@@@*********@******..=_(46446_*              ",
"      {jmoommoosootuuqqutsmmj[0kkkkkkkkkkkkkkkkk2&aiiid}**********&&'***&(4*!!+&******&******+..=__6444a(*              ",
"      ogbb00bjmmmmmmmommmmb]{[/>2kkkkkk5jkkkkkk0#'(}6ad6(&********@&*****&*&*64.******&*****&...,__}a44a(&              ",
"     =      {,~{||25gm5[|{^cgp0+jpkkkk2+bkkkkj2@**&&&&4*&&******&..******&&_ada&@*****&*****....^___}664_*              ",
"               ^^^^1^~1<~2gmk2-+)kkjk5>.+5k5]@&******!3&*****&$++#;%+&*$&+ad46!+.*****&&***@....^____aa__*              ",
"               !_}a446(_!0kk/+-5)20]j%%@2>g.*********!!&***@.@....+kg/>$@'}**&********&&**$+....(____4a(_*              ",
"               !__a446}_!5kp55]/gkkkppj%kk]&*&********@**&+$20@....%j/@**&@*@&@&******$**$#....@(____a6(_@              ",
"               '_3a4444((:kkpj@-jkkkkp:+50@&+..&&********.:)#jb.....].&&&@************.%-#.....#_____aa(_#              ",
"               ,_a44446__;kkkp)/pkkkkp/%p;a._+.'@++*****@2k;+jk/....a'$6!&.&&+&******+%jp:.....%(__(46a__%              ",
"               -3a44446__*jkkpjgpkkkkp55k,'@i.ir.+!&**&&$jk-+gkp)..}r+v_.i3@+(@****@./pkkk#..+.%___4a4a(~>              ",
"               %164444a___/kkkppkkkkkkppk)>r.+z!%a*.++..)kk%@gkkp-.i+3}.av@.ir&***.+jkkkkp5....=___a446}=2              ",
"               -;a6444a(__)kkkkkkkkkkkkkkk%,g'a):=:025bgkkk%#gkkpp#..!&.i*._d.$*@..5ppkkkpp/...!___64444@b              ",
"                %(a444a(__*bkkkkkkkkkkkkkk0bk.:kbgkkkkkkkkk%+gkkkpk#....#g0%>b:+....)ppkkkpp).+(___644a_%               ",
"                 ,}a446(___*0jkkkkkkkkkkkkkkkjkkkkkkkkkpkkk%+gkkkkp5+..../kkkkj+.....;pkkkkpb%!____644a*2               ",
"                 %(_a6a}(___*2jmkkb-jkkkkkkkkg2pkkkkkk2-5pk%+/kkkkpp%....+bkkkkg......2pkkmm{'____}64a(@                ",
"                  ,__a46a43(_,{cmj%%kmkkkkkkp+#pkkkkkp0+5pk%@.bkkkkp0+...+;pkkkkb......jmb8~!_(((}64a}=]                ",
"                  %^_}a44443_(~={0b%-;5p0kk5;..]kkpkj>>#%>k%+.%pkkkkp].....bpkkkp:.....20{'(_(4666a46!%                 ",
"                   %__36444a____^~)5g)%j;kj.-#..gk)k0/j#g/b%+..]pkkkpk>....#jkkkkk).+.*'!!____64444a<#                  ",
"                    '__a44444(_((((,-]]55jj:p%.00pbkjp:.bkk%....]pkkkpg@....)kkj522='(________644443%                   ",
"                    $!_a444464366a3__(!'!,>/5%#ppkkkkp>.>kk%.....gpkkkp:.....2g;!!!(__(_(____66444a-/                   ",
"                     $!aa666666444a}______((!'=5jkkkkp:.0pk%++...#kpkkk0%$,'!',!_____(464__3a64444,:                    ",
"                      -*(____3644446___________!,]5gkppbkkk%+-....-5g5)~(___________(4646aaa66443*:                     ",
"                        @'(____644463_____(______(!*-/gkkkk%#:.....@*(__________(___3a4444a3(_(!%|                      ",
"                          $*(__44444a6__3aa3_________(=0kkk-+b;...$(_________3a643}664444a}__(,%:                       ",
"                            %$'(46664aaaa446a(_______((=5jk-+bb+.'_________3a6444aaaaa66a__(!,-                         ",
"                              )%$'!_}36644446a__________!>j-+bk%!______}}6a6444446a}!!33_(*%                            ",
"                                   ~(__3a66446a_6aaa}(___(=;+2](_____4aa6446644464((@)$**$                              ",
"                                     >-{{<3344ad6444a}____(+.$(____}a4444aa433_!*$->                                    ",
"                                         #-{^_(3a6444a____($+!_____a4444a6_!&={                                         ",
"                                           ]%%=((4a446a____(@____}a4446a_'@]5                                           ",
"                                               %'_364466(______(3a444aa(%/                                              ",
"                                                ]@(4aaaaa4___33a66aa6*%                                                 ",
"                                                  -*(((_66aaaa4ad3__%                                                   ",
"                                                    =!___4a4446d__1;                                                    ",
"                                                     -*___3a44d3_<>                                                     ",
"                                                       *(__44aa(()                                                      ",
"                                                        =__}ai}_-                                                       ",
"                                                         *__aa_-                                                        ",
"                                                          ~___!                                                         ",
"                                                          %(_($                                                         ",
"                                                           '_*                                                          ",
"                                                                                                                        "};
