#pragma once

/* XPM */
static xpm_row_t const ravenclaw_logo[] = {
"120 146 65 1",
" 	c None",
".	c #191A37",
"+	c #1F1A21",
"@	c #1B2359",
"#	c #2E231D",
"$	c #1D256F",
"%	c #352E37",
"&	c #302E4A",
"*	c #3A2F29",
"=	c #392F30",
"-	c #401DF1",
";	c #3F3120",
">	c #3927AF",
",	c #3C26CA",
"'	c #463517",
")	c #4930EE",
"!	c #4039AB",
"~	c #44495D",
"{	c #42496F",
"]	c #62452D",
"^	c #554930",
"/	c #70431B",
"(	c #4C4B4F",
"_	c #524B42",
":	c #694A1E",
"<	c #4F4A9E",
"[	c #5646D6",
"}	c #5545EA",
"|	c #495990",
"1	c #4C63AF",
"2	c #586484",
"3	c #7F6031",
"4	c #8F5C2B",
"5	c #866228",
"6	c #77684B",
"7	c #666D6E",
"8	c #916721",
"9	c #6366DD",
"0	c #6E84A5",
"a	c #7580C0",
"b	c #5387EF",
"c	c #538BDA",
"d	c #A87F3A",
"e	c #7283DB",
"f	c #B1812D",
"g	c #698BC5",
"h	c #848C8B",
"i	c #A68D5E",
"j	c #CB9631",
"k	c #CC9647",
"l	c #7FA3F2",
"m	c #C19E4F",
"n	c #8BA6C6",
"o	c #9FACAA",
"p	c #8FB0EB",
"q	c #A2C5EB",
"r	c #EEBD48",
"s	c #E5C069",
"t	c #E3CB97",
"u	c #C2D1D1",
"v	c #B3D5E8",
"w	c #79EEE6",
"x	c #A1EAF5",
"y	c #BCF3F2",
"z	c #DDF5F5",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                 ^                                                                                                      ",
"                _*^6                                       ii6666                                                       ",
"                _**_^                              _]^]^^;;;**;*;;;;^^^_^                                               ",
"                **;;*;^                       ^^;;;#;;**=*;;^''';;;^^^;;;;;__^6                                         ",
"                **^^;;;_^                ^^^;;;;;;##;^^66333i3633336^'''';'^^^__^^^^                   ^^               ",
"                ;*^m3'*;;^^66       i^^^;*;;;;;;^6immrrsrrrrrrrrrrrsrsmi3^';'';;;;*;;_]              ]^;*_              ",
"                ;;6skd3;**;*;;;;]]];;;;;;;;;'3msrsrrrrrjffkkd88fdfffjrrrrrrrmi3^'';;;**;;;^6i   ^]^;;;;#**              ",
"                _;^skjkd3'''***;;;;;;;;;=;:3mrjffffjfffff8:5ddd5dmdmmmjjrrrrrrrrsm3:^';;;;;#;^t^;;##;;_^**              ",
"                _;]sdkkjkdi3^^';'^33388dtmffffdd^'5msssrjddsiimi3ddffjjmdfmmmkrsrssrmmd6^;''''';;''^6tsi;*              ",
"                _;^kdfkmiidddd43353588888ddissrs5drrskdd5iksrrrrs855544jk:mskmdmrjrjjjfd55:''''':3dkrrrd;;              ",
"                _;^kkkdttjsm:33ddiiiifm:srssssjdffk88di58jk88ffjj8/35:/:5::fjfjkj88dmmfmi5555:':58fjjrri;;              ",
"                *;'srk8tmdddmtsssssrsrfdjjkmmdd5d8d55::/3:5d5fd4/]:454::::::5m4fkmddfkjrrrjjfd5dtsd5fjrd;*7             ",
"                *;'ssf4sm3dkssmkkddkjddff4dff888855:54/:55:]]]]:]3kfd444444/::8fffjjkd:38sfjr5:8ssjf5frd;*              ",
"                _;;5sd4dsm53dmddiddd53ddkdd85354/555dddd33^_(%&&&~_5dkd448855:/5488fmmd3335ddjsd3sjf4fj5;*              ",
"                 _*'if45rrm3fjf85/35444::3334858fkfkmm6_%&@!,})))}>@%^imfddff85455/:/::/44//ffjjdrjf5fk3;*              ",
"                 6'':555mksm35433455555488dffkjjkkd4]{<>,}))----)>!<<<&(3mkkfdffd8445553/::::dj5mkj48fk:;*              ",
"                 ;;;;:5ddjjrd445dkkkjjjjjkkjkkf4]_&<[)))}}))))}>>>>>!!>[!&]djfkffkffd8443//:5388rfj:5fk';*              ",
"         ]]3   _^;;]345j8dfr88dmkskjkkkjkkd3];&$![[}}))))))})>!>,,>>!99))[nh_3dmkkkkjjkfd443/43kjfd44fd';               ",
"    _^;;*****__;*%=]53isddfs853^_(((___~&&&<!!,)}}[}))))))})>>>,>>!<qv9))[qyyo{$&_3d5ddd344554/jfk544d5;;               ",
"    *=%========%%{|a1|~_63ss//:ia}}pzze}!<<!}))),)))))))),,>,>>!!!!vyy9))}pyzze)[9vuo@$@${&]3/mff58/48:';_              ",
"    %%&||||a1|&%|llllllla|(_]:^ha}}pyva,!<![))))))))})}),>,>>>!!!,9vyye)-,qyyz9-),qyq[-,[,[&]drjm88:48d';*              ",
"    %&<9lelpppe|lla|2aelleela~*7a))lva<>!<,),[))))}})}},,,!>>!!![)[vyz9)-}pyyz9-))qxv[),)-}@;8jj588:58d:';              ",
"    %%|eeblplpa2(==%%=~20plplla2{>}a2<!>>)))))))))}})),,>>>!$!<>}-[yyye)-}pyyz9--}qxx<,)))}<'/:5ddd:553:';;^            ",
"    (&{leelg~*+=*==##==%#*0ppelp|$[|<!![)[)-))---)-),),!>,>$!1v!)-[xyya)-}gyyy9--}pxv!)---[<;]]:]^_;__=%%#**;_          ",
"    (%{lla{===%=***#=====#=~pllla@>>!!,}-))))))---)},,>>,$!>pyy9))[vyyp--}gxyye-)[qn[)-}[<|~(houhzovzzuvuuh2=#*^^       ",
"     %&a{&===%%=*;#*=#%%=*=%alpp0$,!,)))--)))))--))),!>,!!>,qyy9))[vxyp)-}exyxe)}[<[[!<~(0nzzzzvuznzzyyzzzzvq|%%#;      ",
"     %&&.%***#;;;;#===*#=**=~qpp~&<!)---)))---))),>>,>!<!,-)qxye))[vxyn)-)exxya!<@|2houuzzzzzzzzzzzzzzzzu0vvqpq0~#;_    ",
"     *%%%%=#;;##;;*~0%=#****%gp0{~=&<!}))---}}))>>!!>$$ae)))pyye,}[vyyq[>!2h7770nvzuhzzzzzzzzzzzzzzzzzzu(~pqppqvn=#_    ",
"    ^;#=&1{=***;;;*7vv~=#**#+2p{elnh(~(~{<!,)),>><<>@$0yp))}pxyn<<{77772~0vuzzzyyzu(7zzzzzzzzzzzzzzzzzu(%%alppqqv(*_    ",
"   _*;=&el0=**#*##=hvyv%****%&l1|aqzzu(=%%%&&&%%%%&&&{hh7$<{(77(70uvzzzznuzzzyyyzo_=7zzzzzzzzzzzzzzzzo(%%&2ppqqqz=*(    ",
"  _**==&eep=**####=nvzy7=#**=%el1|pvyzzh7zzun022000nooh000ouuzzzzzzzzzzzuuyzzzzz7**=(zzzzzyzzzzzzzzzzv~&%&&lpppvu==     ",
" 6_*=_=%|ap~*#####=vyyzh**;*=%|pg|pqzzzzoyzzzzzzzzzzzzzzzzzzzyzzzzzzzzzzuvyzzzzzh===(zzzzzuzzzzzzzzzzzq2&%&alpqvo==     ",
" *;% ^=*%|p2=;;;**=vzzzu=**;=%{pp<lqvzzzvyzzzzyyyxyyyyzyyzzzzzzzyoozzzzzzzzo_6uzu%##_zzzh__ozzzzzzzzuvvn%.+aelqzh==     ",
" ** _**=%&p0=;;;;;=vzzyz***#*=2le<lpvuhhouzzoh7_*o77ouzuh__hzzzzo(77**6zzz7**#_oz=##(zu_*==(oo_((((u(hvp&+&1lpvv(=*_    ",
" *_ ((=%%%0n=;*#**(yzyyu*#**=%npl<9e2=;#;_uy((===uh%*oz7*=*;hzu6***;*=*uzo=#====u(##7u(=%(=*7u~===7u=(vq{+&1lpqu=&=*_   ",
"_*(    =%%0n=###**(yyyz7##**=~ppp|e|%%=#**7yo=**(zo=*oo**(7**o7**#*====oz7==h(%~u7=#(uh%~uh=_u7*##hh**nq|+%1llqh{g2=;_  ",
" =_    ==&0v%*##*;7yyzo=**=%=0qll{91|%=(=*(vu=**7zu(=v_*#hu**(h*==~~**=oz_*(yh2zzh**(zzn7zo==hv=*#h;==2q2+=elpv(1qv7=*  ",
" =;_  *%&&nv%*####7yyy(*;#*=2xqle{1el0~u7*%hz(**hzu_%o*;*oo=**o==(uu=*=oz**=zozzzh*#(zzzoh_#%7z(*#_#=#~p~%&epqu<eqvz7=* ",
" _**;*=&&|qq%**###hyv7=**==2vxqpl{|elpnu7*=7z(==ozo=~h#*#h_==(v(=(uz(==hv**(zzzzzh*#7zzh(=##=(zo=#;##=%a%%&lpvh9lqvzo=**",
"  (_*##%1lpq~***##oz7****~ovyxqpl{|ela(==;_7u(**ozh=7h**#**=0vz(%(uz7**hu*#%uzzzzh*#_zu_*=(#%(zz(%##(%#{%#<lpu&9lqvzo#**",
"    =;#&aepq(***##h6==*;*uyyyxqpp{|a2%&(*==7u(==hu(=oh**##(uuzz(=(vzh=#hu=*=uzz7o7**(z7**(o=%(uz7%%+h2%&%&9lvh<blqzz__= ",
"    _;*%eepq7#**##hh%**;*_yyyxqpp{a~&&%0(==hz(**7o%(vo=**(zz(vz==_vzo=*hz_==ozo*o7#*=u(==ho==%uvn=%&n0.%%&9pz~9llqzh*=  ",
"    _*#%1elq0#**#*ozo=***=7vxvppa@a%%&~q(%%7yh==((=7zo=**hzo%7u==%vzo==7z(*=7o_=o(===n~*=02%==2qn.&{pp&%%<equ|9lpvu*=(  ",
"    (==+|9ep0==#==ozz7=***=nvvpe&||+.%2p===2qn=*&=%nzu==*7z(%~o#==ozh==(u7*##;*~u=#=#2|&.%%%%=&{g&&aqp&=@eevo<epqzh;*   ",
"     (%%&1lqn===%%ozzu%****(vql1.1{+&&~0==*~qq~==%(vzz7=**(==hh**=~v7%=&hn%=*=~n0&&&%~a|&%&&%&{0p{|lpl@{9blv79elqz_*(   ",
"      %+&<lqn%=#%%nzzv7*#**=hql1@||++.&%=%%=7v0%={qvzvv%**=%~v(%=&0n&&@appa&%{pn&%%%%&glleea{gqqpcllpl<eeeqv&9epvu*=    ",
"     _*%&1lqq%##=%vvvv0#*#*=~nee|&!{$&&&{&%&1ppg|pqvvxv7%%%{g0%&|gpa@apppppelppgaagaepppppqllppnnggg0{leblqn@elpzh*(    ",
"     **+@elpp%+##(pqqq0#*#*=%0aea~<1b9eee@<elplpqqpppqqqa|gqq{|pqqppllllllllappppppppnnn02~&%**==***#*~0llp2<blqz(*     ",
"     **&alplq%%=%&pppp0##;#%%~01a{{<eee1e99eeeelpppppaplppppplppppplllleelll1ep00~((==.@@&~(;]^^3]]']#%&%hn&ablvu_=     ",
"     *#&aeglp%%=={lppp~+%=%%&%|10&&|<9991ee|19eeeeelg|eelppaeeelleeleeeeeea|{~==&@~202,-,evh;]:kk4im]*@<{%=&abpzo*(     ",
"     *#{aaaag&%=={ell|%++&%.&&{10=#%%~{{|11&(e9e1eaee|e199e<eebbbee9<|{&&++++.~<>}qzzn--)9vo':5sd5mk:;|9<&*{llqzh*(     ",
"     =%2|1aaa&&+%{ea2&&&&&&&&&{12&=$$$@%%&&++&{|{{|<|@<{||2~2|{{~~&&....@$$<<0n}))qyyn---9xo]]msdmsk:;0pe<#2llqz7*      ",
"     =%2a1a2|%++=~a|~~72|1<<|{|1~%~!--}n0{@$&+&&&..&++.@..@.@@$$!>,,>,>[[!$|nxq)-)nzxn)--9vo']dsmrkf];0p9<+|bpvz(=      ",
"     ==~20022%+##(|{~+=&2||22||{%%2[--[zyv[-,avv0,,,>>,,,[<[))))}[<9,!>!$!>lyxp)--nzxq)--9vo'3dmsjkd/'ae9{#alqvu*(      ",
"     _=~22222~+##=~&#=%#*;*=##..&&0[-))vyv[--eyyq))>,)))[~_[}[)[&;![${|{|,-exxn,--qzxv)--9xo'38stjk5/;19<&{epvvo*(      ",
"     (=~2227~&####+#;^6^^;'';2!>>av9)-}vyz[))9xve>>,)[)<]]&})}<]]*{]_|{n2))9xxp[-)qzxq)--9xn]4dttjd/:;|{&<bpvvzo=(      ",
"     (*=(~%=%+#####'3:dd3i33'u>),ez9})}vyy9))9g<>>>!~<!//'<)[~84'*44(7nv7[)9xxq[-}qyxq)--exh]3msmjd]:*%|elpqnvzh=(      ",
"     _*=+++%=##***;:555j8s/:;v[-)ez9}}}vxye-)!!,![!]_{]4/&!{]44:'/444446_!)[qxq[}[vyxq)--ax7]:msdr5::'2eepqv7zz7*_      ",
"     (**=**==*;;;;;/5m4rm8:5;n[-)ez9)))nxye,>,,!>!]4;~i4'{(3484///44///7|!!@h2{$!<nyxp)--1g{]/j8fm3::;|epn07_7o7*       ",
"     7(%((    *;#;;/:mdks3:5'o[-)9ze}))nyq<),>!<<_44]iu6]]4di4////////:';%&@$$$$$@oyxn}-,<$$'5jdjsd/:;=7(%$@&&***       ",
"              **#;;/:imfs5/5'o[-)9zp[-}ga!,>!$*]]44/6uoooitui3:///'';;'^;%@@$@@$$$2zyq>>>!!&]8jsmjf]5'#==199<|%#*       ",
"              **;;;::d3rkd43]o9))9yp[)!!>,),[&:/ou]]iuuuuuuo6:]]]'+@@@@@@..@@@$$$$@ov2!!!>[@]8rfrf8:5'##%ve1|&=*(       ",
"              *#*;;:/mmmsm8d]o9))[yq!>,>,),!1~]]_hzh]6oooiii:];+*]*@$$@@$$@@$@@.@$${|$!>>,,@]djsr88::';#~|{~%*=(        ",
"              *##^;3/dmsmsdd3oe))[p1>),)},[|uuuuuzu_]4i::////:^.@.%&@$$@@$@$@@$@@$$$$$!>>,,@]8fsk8m/:';#*{l~=%          ",
"              #;;^'::dfrmm5m6oa)>><>,,},)}[<huzzzuh_]/4/';&.+;]]=.@$$$@....@$$$$$$$@>>>,,,,@::jskff::;;#%ap7*_          ",
"              ##;^'::dfrt35m3on>$!,,,-))!2227uzzuh_66444:]~$@@.+;%$$@...+++.@$$@$$$$>,>,-)[&3:msdj5::;;#&ezh#(          ",
"              *#;^'::8drs68m32{$>,,>--)!nuzzzzuuo7_]//]*=~apg|@@@.@..+++++.@$$$@$$@@>,,),-)&::skkj:/:;;=&ezh#(          ",
"              **_^']5:kfsi4m6=@>,,-))))[{hzzuoohoh6]]%{2gccclp|@.++++++...@@$$$@$@{@,-)))-)%:fr8k8:/:'*(=eqh=           ",
"              **7;'355jfsm5d6&!}-)))[[}[aozuoohh7(%~|bbcpqplg02hh++++..@@$$$$@@$@0n@,----)[=:jjfm3//:;*7#|q7=           ",
"              ** ;;:54jfrj5di@,)})}}}}[0uzuhh7~~@$$$!9bp0|{72huuu++.@$$$$$$$@@@2qn|>--))-}[=:fjjkd//:;; *%p==           ",
"              ** *;]35dkfm5mi&})})}))}<nuo(&@@@@$$$$!9lg@+7_7xhzu.+@@$$$$$@$$|nxg{$-))))-}[=:kjdsd//:'; *=0=(           ",
"              *( *;]53dmfm3ii&}[[}[}[}!&~&@@@@$$$@@@!ec$.+h0oxhuh..@$$@@$$${0xq|~$)-------[;:jftmk/:]'; _=(*(           ",
"              *  *;'/5mfkf3mm([}}}[}}<&@@.@@$@@@....$b!@.+_yh{|.@@.@@@@@@@2yvg2~<)-)-----)<=:ditdj:3:';  *=*            ",
"              =  *;'/5srmd:fs_!}})}!@@@@@$$$@.++%~~|cc<@..+&@{9@$$@$$@$${nvpg~&$)))--))-,[$_:ittdj:3:;;_ **(            ",
"              (  (#'::srs6]dm6$}}!{@@$@@@@&&%%~~{{21cc<$@@@@$@<$$$$$$$@0yqc|~+$-)))-),))!!@_:mskfk/43';; **             ",
"                 (*'/3mfsi:dmo%<@@$@@@..&~%&||{{21|alb9$$$@$$$@$$$$$@2vvpc|~.!)),)-)},,>,,@*3ss8j5/45';* **             ",
"                  *;:5ddmm:ii7%.@@@@@.&~~~{nh1|2~%~{gbb!$@$$$$$$$$$|0zvcb{~.>)-),)),>>>,>>&]4rffk///3;;= __             ",
"                  ;;:33mii^*&.@@@@@.&~~{~~2hn2~{$@&{2cbbg|{{||000nvyyqcg2~.>}-,,>,,!>>>>>>*]dk8j8//46;;  =              ",
"                ^'#;'436(..@@@@@@..&~{|2h{g072h~@&{||gccpnnyyzzvzvqpcc1{~.>))),,,>>>,>!>)>']kdkj5//d';_  (              ",
"           :';'###;;#^;..@@@@@..&&~{|11gag0(7ho(+.{11||gccgqq0nplcccc|~&+!-,,),,,!>>>!})-<':kmmfd]:3;'_                 ",
"          **###++...@...@@@..&~~{|1|11bbg77uhhoh+.@<1|1g1a|g070clcc|{~~#@,,>,>>!$$><ql})){:4rjdj8:3';_                  ",
"           =#+%@|@@{.&{{~(~~~{{|1b0gbbg27zuzo7uu+++&|||||1|~772cg||{~~%.>,,>!!@$$>eyzq}-}&6drdrj8/3##(                  ",
"            (=*~|bbb111111111b1bbcagc201ozzzzhhuo&++%~2||{~(h2gg2~~~+%+![,>!!!$!,-9yxv[-[*38dskk54:#*                   ",
"              (=%=~|gcccbbccbcbbb1|{0xy<nuzzzzhhuo%+++~~{~7hh(~~(=++%%&>>>!!>$!-)-9yxv[)!]3/ssdk543;*                   ",
"                =****_7670007(7(*<99vyy99<uzzzzohouh~~%.20h77*=#+++%~%@!!!!$2q9))-9yyv[}&3:5sd8d:8:;_                   ",
"                 (*;':3]imi6i6ti#!}9xyy9))oouuzzohouuuh7oohh_##++&%~~%<!$!$0xy9-)-9yyv!>^3:ss4j5/d';_                   ",
"                   *;]3:8rrsi3km;@)[vyye)->{oooouuuuoo7h7_7_;#+%~{~~~.>>$!evyx9-)-9xyq!{35frfdf/8d';                    ",
"                   =;'33/dkrt68k3=>[vyyg)-$&]]7hhhhh7__((_##==(~{{~~~.!!,)9vyx9-)-9xyp<_53rjdk5:d:;*                    ",
"                   (;'333:mdst6ki;$[vyyp})!_/467__7__7_+#+=_(((~2{~~=%0[-)[qxxe-)-9xyq~i:jjkj5//d;=(                    ",
"                    **:55:5dfsimk3*!xyyg,!!!{//67**##*#++(_77(2{||{~#7y[-)[qxxe-)-9xyo6ddjffd5/48#*                     ",
"                    _;']35:diksdjd;{qye!!,!<<=/4o*#+++++#_7_777{|1|~*2x[-)[qxxe-)-9xv6f5rjfmr5/f:;_                     ",
"                     %;'35:5mdjmfk3*0e!$>!!&]]3ih(+++..+#_77777211a~=0x!-)[qxxe-)-9x7i5djkmkk]58;;                      ",
"                      ^'54]5jdks3km]%!!!!>,[=44ouo..+.+.+(777772b1c~%0x9-)[qxxe---9oid8:mskk5:8:;_                      ",
"                     _*;553:krmmm5kd*$,>>>)}[&/dih.@.+..+7hhh701bb9|~0x9))9qxxe-))<^m4:dtk8s555';_                      ",
"                      =;355:irstm5ds3&>>}}))[}$/4i_@...++7hh70cbbbb1g~o9))9vxyl))9_d4::tsffk:8];_                       ",
"                      =;:55:3kfst63mm^@)}}})}}<=3o6.+...+huon0bbbbbbc(%|[}[vxxa}[(d8:6tkkdf355;;                        ",
"                       *'343:4dfst5dsm%!)}))}!]]io#+.@@.&uuwwwgcbbbcq7%+{9<xxxe9&dd3iskjdf3:5';_                        ",
"                       =;'d55:5ffjrdss6&>)}}}[{/i6++.@@.2zuwwwxgcbbcxh2+.&{vxyn&35dssjfff5:5:;_                         ",
"                        ;^:d5::fjffsmss6&}))}!(:3#++.@&.nzxwwwxglbbgww77..&(7o6633skdfjf4:33'*(                         ",
"                        =;'33333fjsrsfks]@})}!_:#+++@@@{zzwwwngbcbblno7hh&@@~_i8dmf8frf:55d';(                          ",
"                         *;:d333tsmmsi8km*<}><%%+...@@@nzuwwngcbbbbbgnwouu0~_mfddsmmf8///3:;(                           ",
"                         (;'33358rrss6:fkt;~&&@@.@@@$$|zzywwgg|1b9bb|0wwzzt^tj4343ik35//3]**                            ",
"                          _;;333/fkksti3ksi;.@@@@@@@$@nzuwww0g1|191|10wwwo6mm8/3isjj5/:::'_                             ",
"                           _;]3353ifkrtt8kkt;&&&@..@@0zzowwwngc||11|bpwwh_sj4]3isjk5:3:';*7                             ",
"                           (*;]5/:3dddmssdfjt_%....@~uzuwwwwwnc1||1bbnw76sd3ittmfk8:::];*(                              ",
"                            (*;:5:3:jjfjrs5fkt;&&.+~ouuowwxwx0cbb1bbl2_6i5dttkffj8:53]'*_                               ",
"                             (*':35:35ddmmm:djm_+&.7ooooxxgg0ccbbbbc26tidmkddfjf5:43];;(                                ",
"                              (*;:d4::jrsssm348m6*7hhhhoonclcllbbbg76sd3smddf555443];;_                                 ",
"                                (;'85:5rrkjsst65dm^^h7hhh2cbcccbb0_im8:3dimmkd585:''^_                                  ",
"                                 _;'33:5sfdjsttt55mi'_hhh7|9bccc7^md]6iisskfs/::'';;(                                   ",
"                                  _;:d3:5rd8fjsrrm:fm];7hh|bbc(*6m5ittssjf5sf:];;_~~                                    ",
"                                  (;;id5:dsskkkjjrs3fmi^^_0c2(6mm3imdidddmmd:3''_                                       ",
"                                   =*'338]:drrrrssss]8fki6;'^imd:ikmdd8845:::^;*(                                       ",
"                                    (*;^355355558mmm3::55d545d833dims5:::::]^;(                                         ",
"                                     (*;']354453:frrsm6633dd33:3isskk:54333^^(                                          ",
"                                       =*;^3ddd5::5jkkjssmmmmtttsrfd:::3:]^;_                                           ",
"                                        (*;^imddd3558ddfjssrrssjddi3:533''*(                                            ",
"                                         (_;'3df4853335dffffddddm3:353]'*(                                              ",
"                                           (;;^8jfd5333:58ffmid8535dd3;*(                                               ",
"                                            (**':frd545855445885/:::;;*                                                 ",
"                                              (*;':mdd4488545555:'''*(                                                  ",
"                                                (;';]dkdd35344d5'^_((                                                   ",
"                                                  (;;':5dkdddi:;**                                                      ",
"                                                    (=;;;:34:'**(                                                       ",
"                                                      (=*;;;;;=                                                         ",
"                                                        (%===(                                                          ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        ",
"                                                                                                                        "};
