/* XPM */
static char * C:\Users\debor\Documents\GitHub\LCOM_WizardsChess\Assets _ Buttons\Button _ Board House Logos\slytherin_xpm[] = {
"120 146 65 1",
" 	c None",
".	c #080E0E",
"+	c #131C1B",
"@	c #171B1F",
"#	c #0F201B",
"$	c #172A25",
"%	c #21292D",
"&	c #3B231E",
"*	c #262925",
"=	c #133129",
"-	c #5A211E",
";	c #512808",
">	c #1A372F",
",	c #143A31",
"'	c #173D2F",
")	c #263935",
"!	c #36352D",
"~	c #30383C",
"{	c #15442F",
"]	c #1B473A",
"^	c #114C3B",
"/	c #304643",
"(	c #6F3715",
"_	c #3C454B",
":	c #654217",
"<	c #105C46",
"[	c #5E473F",
"}	c #175E55",
"|	c #A5372C",
"1	c #495555",
"2	c #49555E",
"3	c #8F4F14",
"4	c #2A6F62",
"5	c #207176",
"6	c #54655E",
"7	c #57646E",
"8	c #875D17",
"9	c #815F2F",
"0	c #DF442F",
"a	c #6A7273",
"b	c #64737F",
"c	c #837B58",
"d	c #3C938A",
"e	c #B3781F",
"f	c #73838F",
"g	c #7B8384",
"h	c #A88121",
"i	c #B9786F",
"j	c #86939F",
"k	c #8A9494",
"l	c #C99923",
"m	c #7DA89F",
"n	c #BD9875",
"o	c #99A4AF",
"p	c #C3AE76",
"q	c #AAB3BD",
"r	c #DAB12E",
"s	c #EFB63E",
"t	c #F8BE1F",
"u	c #BDC4CC",
"v	c #F3C828",
"w	c #D0D5D9",
"x	c #F7DB64",
"y	c #E1E6E8",
"z	c #F4F7F6",
"                                                                                                                        ",
"                                                            zyyuw                                                       ",
"                                                           ywquuuq                                                      ",
"                                                          yywj2_fqa                                                     ",
"                                                          wyu   2f7                                                     ",
"                                                                fj_                                                     ",
"                                                               qj2                                                      ",
"                                                              oj22  o                                                   ",
"                                                             qq2_  gg                                                   ",
"                                                            aob__ fjf                                                   ",
"                                                           wuuwu222j                                                    ",
"                                                         zyyuuwu2222                                                    ",
"                                                        qwwwuqjf22222                                                   ",
"                                                       uuuuuuqqof222_                                                   ",
"                                                       yyyuuuofbfb2222                                                  ",
"                                                       ywywwwqig[[[_222                                                 ",
"                                                   iiiinuyyywi00|||||[2_                                                ",
"                                                  i00000ikywuw[--&-|||||                                                ",
"                                                 zzyi||&&-[722_&&&-&&--||                                               ",
"                                                zzyuq[---|[27bf7&-(-&---(                                               ",
"                                                wujf77[--&.@@%%%%%@&@&&&-                                               ",
"                                                _bb7~..@....@%%%%%@@@@.@%                                               ",
"                                                 2%...%~a%27_~%%@%%@@@~@_~77                                            ",
"                                             uujg@@%.~7jo7of77_%@@2%@@b~~2~b                                            ",
"                                            uoo7~%%.@ojofjjb772_%@%b@@b2%7_b                                            ",
"                                            _j227@..7jjq7jjb772_%@%22@27.@~%_                                           ",
"                                           a._7f2@._qjjq7ojfb72__~@%b%@b%...@ ooo                                       ",
"                    zwu                q    ~oyg%2.awuuqoqqqbb7272@%22.7_....ffoqq                                      ",
"                   zg@~q      wwwu    uuo_  jzy~7~@foqwuob272~b7~@%@_b%_7...@j%joo                                      ",
"                   w_+%ay    wuqqquuujqof2%awzg7b.%oqqqffffb7_*b__~%%b7@7%..@j7uqo                                      ",
"                   yqg_2y   oa_~~_27jjfbf%@7zkgu_._qqqqjfffb7__bbf7%%7b@27...bbagbbbbbbbuww           u                 ",
"                    yu%_   a@.......@2fj2.@_g1zo@.jqqqqjjjfbbb7bbb7%%7b@~b%..@b~%2bfffffjow       wuuqu                 ",
"                    w_%1 w_..@%%%.....%...@%~wy1.~zyuuojoojbb7772_%%%7b@.bb_%..%@@@@@~__2aju     w%auuu                 ",
"                   uq@2wya.@7kuuug1@....@@@%gyg..@uyywuqqqjb72~@722~2f7@._f27_@~22~@......@1k  yuk+awuw                 ",
"                   ya@owu++gyzzyuqug@%%~%@.2uj@.@@awywuqj72222272277jf7@..fb2_7b2..........@~kyyug+%gw                  ",
"                   y7~ww7%7qzzyujoqu@_quq~_jf2@.@.kuqqb_7bbb772_7222fb_2@.%f2.bf7_..@@@@@....%uwo7+~o                   ",
"                   y_7wy7%jyzyoafjow~bjfofff7%..@foquwqfjfb7777~7_%~~2ff7..2f2_bbb%.@1oqjj2%.._uoj@_b                   ",
"                   y~juy2%qyzk%.2fjq7f_~bbfb_@@@aojjwwujjfb777727_@g.2bbf7..2f7222@@kywg__7b@..qoj_%2                   ",
"                   y1oqw2%uyo~..ofbj77.%7bf_...1qq21uywjjffb777772@u%@ffbff..~b7%..1zq*+....+..7qjb@2                   ",
"          55}5d    yqjqub%qyq@..___j_7@.27%...~uub+*wywjjjff777o2b~ag.~fbbfa@.._~.@ou.+~_%.....%qjb@2                   ",
"         55d55555  yygqqq@gyu~@..@b_.~~......_uuf++#qywjjjjfb7777b2_q%.7fbbjb%...._q7~jqqo/.....qj7%7                   ",
"       155555dd554^awuugw_1uw_277b2@@@@@...@auuj%++.oywjjjfffb7bfbf1~@.@7ffbjo7@..1q7oooboj$...+oj_~7   4dd44<          ",
"       ]^^^^<<<4dd^=kyuqkj.jua..@.@@@.@@@@@azwo%.++.qyujjjjfboojb7b%.ao.%ffffqqq7._qfqoqqbq)...~jj~~  4dddd44<<}        ",
"      )$='^<^'##=}^,=1oo7o2%ff_...++@@@@@~gwwj_++++1uwujjjjqqjb___7b@%q_.~foojqquwuwoqquujq/.++2jb~~ dddd4^^^^^^/       ",
"      $.#,^^=..]}^^'=+_jjaf7%bb2%..@..@~7ouo7)##++%jwwqjjoob77722__b~.%j~.%fquqouyyyywwwwuq)#+$fj2_  dd}$.#$=,^^]       ",
"      $..$^]+.#dd^,=+.+7jf7jb~7ff7__277bqoj_+$#$+*guwwojjojjjffb722jf_.~k%.@7ouwqjuyyyyywuk$$$/jf_   d4$,=.+$$,'')      ",
"      $..=^]..+4<^'+.#]/fj7~27_2bbbbbb772~@.#$+#+gyuyuooqojfffff7272jj%.2j%.._jqwyqjooqqqf~$/>bj7%  6}<^<]..+$'',=      ",
"      $.+$'^$..#''#.+]<{$7jb_~_2277772_~@+%)  +$gzwyyqoqoojfffjjjj2_7oo_@7o_#+%2fqwywuqojb2/>7jb$#   ]]^^$+..#=,'=      ",
"  ]<^^,$##=']$#..###,^{###_ffb_~%@@@...+%_   ++gzwyyyajoooojfqqqooo222oo2@_o7+##%_gquuqo7/)/bf6}'+.   )/)  ..#=''=      ",
" ]<]']>=$$#$=,$####=]^##$###~7bbb722__72     .qzywzzz7joooofwuqqooob__~uq_*_uk@+#+.+$))>)1f7)=<<<=..      %..$=',,      ",
" ],,,^^)$$##$$$##$$='#.#$##$$$%             $aa6qzzzg227oooqqoooojjb7fjfqq#$$*_#####+#$$)%###+{<<<=...   *.+#$>'''      ",
"^},]^^<  $$$$$$#$ $$+.##$$$$$$          $$$$##$=/zzzy2oooqqqooooooooqqog71=====$$$#$$$###$####.^<<^'$....#]}]='']^}}}   ",
"<^,]^^]          @#.+###$==,$$   ).#$$$$$$$==$$$$kzzz7ooqooooooquuqg1>$=$=','',>>=$$=$$=#$#$#=..^<<^}55}555d},'']<4}}54 ",
"6^,,#==)    //>/)$..$,=#$,'=$$#{=',>=$$==$=$>=,,=.wyzojoooooquuqg/==,===''>>>=,,=>==$$$$$$###'=.#]<^'>}5ddd/$'''^<#..,< ",
"u^]<]$=>$=]}54}'#..$^^$#,^=$#$>{',>$'==,=$===''>=$ayyojooquqga)==,,']'=,>'>,==>=>>>=,>=$$==*#=^$.=]}^^}]===,''^}^]$',$'4",
"zg^}}]=$,}<<}]>$..#=,=#=^,#+$='^]'','='^$=>>>>>>>$)uzqjuwk1)==>'']]^'',>>,'>=',=>'=='=$$$$=1.$^<.$#=}}}}<,'''}dd<<^^<==<",
"zw}{}}=]<<<^'#...='=$#$^'$#*>>>]^]',,=,]'=>>>$=>>>=6yqug##>=^^]]]^]''',>,,=>>>''''$=,=$$$=, +#$<^.>..]55<^#,]^^]'{]^<'#<",
"zzw6]^]##+....+#'{'=##'}=$  $='^^^]]',>=$>=>>>,>=>))aa$====>,,''','>'>=,'>=,='=>',==,'>>=$=  +='<}+#..+]}<^#.++..+={<=#}",
"zzzyk/'',==$$=]]'']]'>^]$$  #$'^<<<^^^,==,>>,,>1akoqooga/$=>^,'>'',=,,''''',>',>'>=$',,>==$  .=''}}+....+=''#+##$''^]#$m",
"zzzzzk>=$=,,,,'{^^]'=,<,=#  #^<^]<^'],>>>,>,,/qwyzzzzzyywq/=>$=>,,''===>==']'=,>====,,=$==$  .+<$'<}#......+#='==]^]$+6 ",
"zzzzzz6,>=>$$$']'',>>]]$>*  $''<<<<]'']>>>'>1yzzzyyzzywyyyya,='',]'>>>,,,==^^,>'==>>>,>$==>  ..,{##^^#....#''=={<<'#+)m ",
"zzzzzzq>>$#++$$$#/#+$,#=,+  #=]]<<<<<''',,>1uyywuojqqqqquwww6,,,]]>,,>,,''=']^]''',',,'=$$)  ..#<$$#=^{=$####=''>$#./m  ",
"zzzzzk/'#..$))$##1.@+.#>,+  +#$]]{]]','],>$quuqj2~_oooqqquuuo)'']',',>>>>','^^^']>^]==,=#$)  ...<$#$=##$###$$=#+...)    ",
"zzzzk,'#.1uqjf7$#1+@+.#'=+  #,'>,',,,,],/)wu72_@%@fqoobjqqqqq1$',,>>>,'===]^],]^>'#$]''==#$  ...<=.,^^'........%*       ",
"zzzk''#+aywj7fjjb_@@$'=']#  $^],,,]',','/uzzyk1_gwuqoj2_jjqqqg$'>,>,>1a/$$=$=>=='=#$====$$= #...<,.#<]']=+..+++         ",
"zzq^'##1yyq~.@fjj%+@#,'^}^/ +,'>>>'',>=)ozzzzywwwuqoof__bfoqqj),=>>'au1$$$=='''=,==,,,,=$$={^]#=<=..'}>']]',$.++.       ",
"zw4<$+#wzqj+++%oj#++$,^^<<' +^^^^]]])=$awzzywwuuqqof~$)~_7oqqo)>=='/o7$$$$=>'{$='===$>==$$=<<<$}<#..=<=/>]//]'..#+      ",
"zm}]#_gzyob+$>+jj)+++=]^44, +]]],,'>$$#uuuqqojjoo7o7']])~7oqqo)',=$af)$$$,='''=====$=$=$$$]5<<}}<+.+#<)o6)//)]'.#$*     ",
"y5}$1quzwo7+,>#jj_.+##,^<^> )^]]^]',>=#wwuqooog77qa'''>$~fqqqo~$$##qf)$$=>>]'===,>==>>$$$#,=.=}<=+.,'^)of//1_),=.##*    ",
"u5]+ouwzuo2#/)$fj_.+**+=],  )^^^^^]]'=#ouqjj_~@2og'',,,$7oqqok$#$$#uf)#$=']]===>,'>,>'=$$#$$.+=#+#.]},7ojb%12_),#.$+    ",
"m5]%zuyzuo2)_~)bj_.1wy7jj   >,]]']',,>#k%.g~..foa>]'''$/ouuoqg$#$$)wj/#$>^<^'>,]>''''^$$$#$#....#=#$]+oobf2_27~)>..#!   ",
"55,1zqwzqj2___~bjb+gzwbjjf  )=']']]',$#g*&[!~joa),'>,>)gouqoo7$#$$)uo2#$=']',=$==','>==$$$$$7quu6>#++)j +27_27_)>+...   ",
"55>gzywzq~+22~_bjf#ayyffjj  !']]]]''>$=-|-&7jb1>'>>,'>aouyuoj1$#$$$qob~$>''''$,,''==],$$$$=awwwuuk)##1f  )22272//+...   ",
"55,azywwf++27~~7jj~%ouffjo  !,]]^<^{=$&|-)a11>,,>>>>'_qqyyqoj)$#$$#qqjj+#==',=,=='$,^,$$$$1oo~2uwwk.#bj )/22277//+...   ",
"55,%yyuog++7b7_2fof$#offjj  !'^^^^^'>$-!''{'',,,>$>')oqwzooo7$$=$$#jqoba#==$$$==$$$==$=$$$7u@..qwu!#~f  )_2_227//....   ",
" 5}#kwqqg%+bj7__7jj7)7jqob  !'<^^<^,,*|!^^^]'=',,,>)guwyyoof)$='=$$/qoff_#===$==$=>>>==$$$7o..+wwa*%7f )$f___72//.++.   ",
" 55=)oqqj%#bjb2_2bfjgkwyq   ~]<^^^^]'$!&''''','>,,>7quyzooj1$$,]>$#$kqoja$#$$$$==,>>'=$$=$1b@+.wwg_7bf2$$b~~2b71>.$#.   ",
" 55$#~oqk%#bjq22_~bfozzwo   %]<,^^],,,,,''''''',>>)oqyzuoqa/$'']>,$#1qqoo1#>==',>,>'',,==#/22%.kwqbbfj//1jj2bb7/#+'#.   ",
"  5,#+)kk~#aoqqb22_fqwuo    *=''^^^^]',']]]]]',>=$juwywqoj/)$,'],',$)jqqjj*#$']>==,',==$$$  2_%%qwuofbfjbooffb7)+='.+   ",
"  55=##$)#+7oowuj7~~___     *']]^^^^^''']]]]]],=$guwwuqoj1)$=''^'',>$aqqqfj#$''====,=$$$$$   2_~_gjb2bqjooufbb1##]=.    ",
"  55,#+#$%+2oouwwwu1>$$+*   +,]^^^^]],$'']'','>$1uuwwqoj2/$$','^'',=$$oqqjb1#=====,,===$$$    _~~%~_7quojujbb7$#'^#.    ",
"  55}#+#7j+%joowwwwg~b/%.*  +']]^''']''=,',>'>$)ouwuooo7/)$=^^',^'>$##aqoobg$$$==$$====$$$      ~/1booofjo7b/++,<'++    ",
"   }5$..7q_+aoouwwwa@77~+@  *=,']'''','''''','$auwyuouf/)$==,===='=##$/qqojj_$,,=$=,'=$$$#    1)/7bbffbboa1$##=<^.#     ",
"   ]5/..)qo+/oqquwu7@2b2$@. !='']','''']']''>=~uyyuoof1)#=====#$#**+#=#oqooj7+=>='^^'=$$$*  ob)$jo77bb2juua#$=<<$.#     ",
"   }5}...kua+7qwuuq7%~bf_+.  #=,]']],,]{''>,=+owyqooj1)$#='=+1quwywwo1#gqqojj+$===$$==$$#  qj)+ouj__2_fuwk##><<'...     ",
" }5555^../wo1+guywq_+~bj7$.  $'']^','']''''=$awyyqoj2)$##$1kyzyywyywywqbqoojj%#,='>=$$$$# oq_#_uu2%%_fuug$$)/<<$.+      ",
" }}]==$../ qj~$jwyw1*_7o7).  #=]^^']]]^],''$1uyyujo7~)$$)gwyywwuuuuwwwuuqqojj_#$======$$$1uo%$auw7%aouu6+##$^5}.+#      ",
" <^+....#   qj$~juyk)77qf).  $,^^^'']'']'>=$jwywqof~$$=)qwzwuqoffjjoqwwwqqojj2#==>>=>=$$$awj)$7wwuuuqgk%##*+^5d5}<      ",
" ]^+##+#%    of)~boj_77uj_+  /'^]'^^','','=1uwzuqq2$$$>oyzwujfb77777bjqqqoojf7#='']>,,=$$kwf))%wwuofb bj$* +}5d5554     ",
"  ]=#$>      j72%~2jf77ou2%  ){]^^]]^'',,'=owzzuqb~$$=auywqjbb7222277bjoqoojj2$$$',,>==$$ wf))#buj   oo1$   ,55555}     ",
"        qooqq __~~~7ojfoo7~  )'^^^<^]'',,=1wwzuqj2)$=)qyzujbb_~%%%%~277jqoofj_)#$',==$$$! uo)>$+7    o7$    $}55}''     ",
"       o_%%qqq ~~~~_jqoayg~  *=]^<^^],',,=uwzyuub)$='1uyyqjb2%%)~%%%%~fqqooff_~$#$=>===$  jj)>$+%   qg$%    !=,},)      ",
"      2.+%2uuq2~~~~_2qob_a%   $^^^]^']'>=6wyzuqj2$>,=kwyyuj7~%)/~~~%~fuuqojb7__~#==>==$$  fj/>$j   oo/*  zz   +#        ",
"     a@@gooqoo  ~~11 wqo~#$   $'^^^^]],>=owyyuqb/$>,$qwyywo7_~///~%_jquqoobb2_2~+=','>=$ of1))gq   q7~ yzywyz           ",
"     7%~uqjjj   __   yojb##   $']^^^],>,/qwywqj7)$''=ouyzwwj2@%%%_kuwuuqojb7_~2~+$=,]'=$ of1)1ou  qk) qyw2~awz          ",
"     _@~w7%_~        wjgo+#*  $=]^^^]''>6uwzyqj2)#,,$juuzywwuuoouwwwwwqojbb_~ko_+$$>'=$'job/)aouyqq// quf~%%gy          ",
"     1%~uj@@@@      qwaaq%+*  +$]^^]],'>auwzyqf_$#',=7uuwyyywywwwwywuoojfb_~awq2+$>',=$/qo7/)gouywj$   wj2~%%yz         ",
"       ouq@+@@@   _uyq@au%++   $,]]^]'''kuyzwqb_+#',>)quuuyzuwwuyywqoojfb_~7uuo2+#>,>=$/wj6/)kqquwu    go7_%@uz         ",
"        wu%@%2uwuoowo2@gy~@+   #=]^',,>,kuzzuo2~##,,$)juuquwqquoqqqoojff_~_uwuo2%$>,,=$2wj6/$gquuuu   _%%%~%@oz         ",
" bf      wq%7uwwuqjjjf2jy~.+   %=]^^]]']ouyzwq7~%=',,>1quqoooojjojjjfbb)~_quwuj2+$==>=/awf1)$1w1jq   %@@%%_%@uy         ",
" bbjf    uufboka7fjbfoboy@.+    #'^^^]'/quyzwq7_%#]^'>$aqqoffffffbfff/#~kqwwuuj_+==>>$)oyf6)$1wy2gwug_%%%%%@7z          ",
" b7jjjbb7bqobb_~gjfb2ofou.++    +=^]]',/quyywub_%.,',==$gooojjjfjjo1$$#1wwuuuq7~#'>>>=)wzjb)/qufqwuqjf%%%+@2w           ",
" g7bjjojf7jof2~b22f7~jjok.++     $,^]]'/uuwywuj2~+$''>>=#aojjjjffb)=$$$kwuqquj2%#>===$ zzob/ayobywo%@_o%%2fu    g       ",
"  72jjjfbb2bf7~7~_b_%boo~@#%     $,^^],/quwywuo2_+$]]'',=$$~_21/)===$$)wwuqqo7_+$===$> zzqb1uw_uyw_%@@77b      o2       ",
"  777jfbb727bf7~%_~)$%oj..+*     *$'''']quuyyuq72%+>],',=$###$=$>'=$$#kwuuqqf2~#==>=$  zzjboyo_uwu~%@@@f      uj2       ",
"  b777ffb7722fff_~~~)%jo%.+*      )'','/ouwzzwuj27+$,=,'],$$=,,=$==$$7uuuqqo72@$,==$)  yybfuwa%yww_%%@+7   quuob_       ",
"  b72_bfbb72~7fff_~~~~jo2.+       *>,''>jquwzyuqfb2++'='''>==','==$$1quqqqqf2%#=,'=$    zjjyu%ajuj2@%@%7 bfjooj2_       ",
"  b7__2bbbbb2~_7fb~~~_fof.+        $,','aqquwzyuqjb2++$'''===,>,$$$1quqqqqo7_+=,,,=/    zqqyo@_ojjb@@@~  77ffjb2_       ",
"  2____27bb72__2b7~~__foo@*         $>''6ooquyzyuujfb%.#,',$=,$$$)gqqqqqqo72%$',>=$     zuuyf@@%~%+@@%  7727bb27~       ",
"   ______27bbbbb2~~___ouo~          ),,']fbqqqyzywuqqqj1.#$$$$#$auuqqqqqo72_+',],$$      uww7@@+@+@%%   77277_b2~       ",
"    2_____22222_~~~___qyo_           >,''1fbjoqwyywuqqquqoggagjqquqoqqqob2_+$''',$       qww2@@+@%%_    27772bb_~       ",
"    722___22______~___uyq             >'''7bbfoqquwwyuuuuuuuuuuuuqqqqqob22@$,,'=)         yy2%%%%~7ffbbbb7bbff_~1       ",
"   zyub__22_______~__7ywq             $>','bb2boouyyzywwyzyywwwwwuuqqj222%@$'>=$          yyg@%f4fjjbffbbffb7___        ",
"  zzyyo222__11____~__qywu              )=>>/7227fjquywyyyzyyywwwuuujb222%+=,=,$$          yyq@@qkj7____2722___~         ",
"  ywwzujkob55566/_~~2yzu             9e9>=>,/7222bfouuwywwwuuuwwojf7222~+$,''$#!          zzw~@uujawuk2_______~         ",
"  uouzuoqf5])>>/)~~~kzzu            99:99$=,=$272227bffoquqoojjfb72221$#==',=$*![   [[[h  zzya@aubboooka1%%~~_          ",
"  qbjyqood4'==)))/_7wzwq      !&[9 33::8hc#====/2___227bbb7bb7222222/$$$,=$=*@&![[ [:[;ls yzzk%@kjjokkmmqywoqyzz        ",
" jo77jjgyo4},>>))/1uzzu      r9::::9::hesx $>=>>)__2222_22222222222/$$=,,=$$+**!!:99[&hvt owwu2@%7bb7bmmdyuuj~7uz       ",
" ojb~_7ozym5}<<}}1qzzwj     vvh:::::98lttv  )>',>>/__2____222222_)$$=,'>=$!!****[988;9svtr qwwq2%%~~%/dmdyqw7%2buw      ",
"  job~2auzzwk}55fuzzwq     vvxx9:::[::evvv   )$''''>>$~~~~1__~)$$$$'''>$)  [@*!9eeh99xssvtr6uwwyb%%%/dddmzkwuqj7oq      ",
"  oqquyyuuyyyywwzzyuq    vvvxxxs8::::::hr      )>',>,$$==$$=,==,]''',,>)   !&9llllletssssvtpaquwyumddddmyzyquwu_oq      ",
"   ouuuuwwuqqqwzzwqq    vvxxxxssse:::::9        $=,>,==,===,,']^^^]>=$>      sstttstttsssvvspaoqqwwmmmwzzzwkouj2jo      ",
"    guuqqquuuuqqojj   vvxxxxsssttse::99          /$===,''=''']^<]]^'$*       sttttttttvsssvtsp_2b2oyyyywuuwwwu_7fb      ",
"     _bjoqqqoofffj  vvvxxxxssvtttttl39             )=$,'',,'']]]'',$          tttttttttvssvvttp*%~%_owwyyyyuq__b2       ",
"       _77777bff  xvvxxxxxssvtttttttsl              $)=,,=',',']>=$           ttttttttttttvvvtt  @+@@~ajjjg7~~__        ",
"                  vvxxxxssstttttttttttt               )=',,>,=>,$           tttttvlrttttttvvvvtv   @%%%@%%@%%~          ",
"                   vxxxsssttttttvtlrttttts             )$,'>=$$*         sttttttv::rttttttvvvvvv                        ",
"                   vxxssxttttttts3;(etttttts             $)>>$         stttttttrr8:ltttvttvvvvvv                        ",
"                    xxxvttttttttl;hr;hlvtttttttt                    tttttttttr3:hrh:stttvrtvvvv                         ",
"                     xvtttttvtttl;ht8e(8rtttttttttttsss         vttttttttttr8re8::893vtrl8stvv                          ",
"                      vtttttvtvtr;htts(;8rlvttttttttttttvvttttttttttttttttl;;vtl;:;::er8;sttv                           ",
"                       vtttttl3lr;htte;lvh;8trrttttttttttttttttttttttrlhltt3;ltt8:h8;(h8vvvv                            ",
"                        vtttt3(vl;hts3:vtv(8v:9hlhlrttttttttttttrrlle8;8:ets8:vtv;hvl8ervvv                             ",
"                         ttvvr(:;:rtl;rttt838:8l:;;;;8r3hllhhl3;&.&:l3;r83tth;httr:httvvvv                              ",
"                          vvtvl::rvv:8tttth;(hvl:v(8:;l(&he;&he;8vh:ve(l88ttv::vtt8:rtttt                               ",
"                            vttvvve3:lttttr(httttv(hr8v3&vs(:tv(:tthtl(:;hsttl;8lvhrtttv                                ",
"                             vttttr8(8lhhth3tttttv(htvv3;vr:9tt3;8:8tt(;;::lvl;;htttttv                                 ",
"                              vvtttvl3;;rv3etttttl(lttv3;;;;8tte(88;tte(hh((:r8vttttts                                  ",
"                                vvtttvrrr:(evtttte(lttv3;h8;8ttl(ltelts(3lveettttttt                                    ",
"                                  vvttttvlelvtttt3:rttv8:vr:8vtr;hv8hte(8lttttttvt                                      ",
"                                    vvtttttttttth-;htvl::re:8tt3;;;(ettttttttttv                                        ",
"                                      vvvtttttttrlhrtte;:83;:hve8elrtttttttttt                                          ",
"                                         vvvttttttttttvrrvvrrtttttttttttttv                                             ",
"                                             vvttttttttttttttttttttttttv                                                ",
"                                                   vvvtttttttttts                                                       ",
"                                                                                                                        "};
