/* XPM */
static char * C:\Users\debor\Documents\GitHub\LCOM_WizardsChess\Assets _ Pieces\WhiteQueen_xpm[] = {
"71 71 65 1",
" 	c None",
".	c #000100",
"+	c #030601",
"@	c #080B06",
"#	c #0C0F0B",
"$	c #121411",
"%	c #161816",
"&	c #1A1C19",
"*	c #1C1E1B",
"=	c #1E201D",
"-	c #222421",
";	c #242624",
">	c #292B28",
",	c #2B2D2B",
"'	c #2E302D",
")	c #333533",
"!	c #383A38",
"~	c #3B3D3B",
"{	c #3E403E",
"]	c #444643",
"^	c #474946",
"/	c #4D4F4C",
"(	c #4F524F",
"_	c #525451",
":	c #555754",
"<	c #5B5D5A",
"[	c #5E605E",
"}	c #636663",
"|	c #686A67",
"1	c #6C6F6C",
"2	c #6F716E",
"3	c #737572",
"4	c #757774",
"5	c #7A7C79",
"6	c #7D7F7C",
"7	c #80827F",
"8	c #818380",
"9	c #888A87",
"0	c #8C8F8C",
"a	c #8E918E",
"b	c #929491",
"c	c #979996",
"d	c #9C9F9C",
"e	c #9FA19E",
"f	c #A5A7A4",
"g	c #A9ABA8",
"h	c #ADAFAC",
"i	c #B0B2AF",
"j	c #B6B8B5",
"k	c #BABCB9",
"l	c #BDC0BC",
"m	c #C1C3C0",
"n	c #C5C7C4",
"o	c #C7CAC7",
"p	c #CED0CD",
"q	c #D3D5D2",
"r	c #D8DAD7",
"s	c #DCDFDB",
"t	c #E2E4E1",
"u	c #E6E8E5",
"v	c #EAECE9",
"w	c #EFF2EF",
"x	c #F5F7F4",
"y	c #F9FBF8",
"z	c #FDFFFC",
"                                                                       ",
"                                                                       ",
"                                                                       ",
"                                                                       ",
"                                +++++++                                ",
"                  ++++         +++++++++                               ",
"                 ++++++        +++czq>++         ++++                  ",
"                ++++++++       ++jzzzh+++       +++++++                ",
"               +++6zzb+++      ++pzzzp+++      +++;_+++                ",
"               +++zzzz+++      ++9zzzc++      +++kzzk+++               ",
"               +++zzzz+++      +++]9(+++      ++&xzzz|++               ",
"               +++pzzs+++       +++++++       ++*yzzz6++               ",
"   +++++        +++#&++++        +++++        +++mzzz+++       ++++++  ",
" ++++++++       ++++++++          +++          +++<[%++       ++++++++ ",
" ++@5w{#++        +++++           ++++         ++++++++      +++]te@++ ",
" ++jzzz<++         +++           +++++           ++++        ++[zzzt+++",
" ++zzzzj++         ++++          +++++           +++         ++1zzzz$++",
" ++qzzz[++         ++++          +++++           +++         ++[zzzv+++",
" ++@iz6$++         ++++          +++++          ++++         +++^yn%++ ",
" ++++++++          +++++         ++:++          ++++          ++++++++ ",
"  +++++++          +++++         ++w@++        +++++          +++++++  ",
"     +++++         ++-+++       +++y!++        +++++          ++++     ",
"      ++++         ++0+++       ++!z/++       +++a++         ++++      ",
"      +++++        ++5/++       ++1z/++       ++&x++        +++++      ",
"       +++++       ++5z+++      ++1zn++       ++/z++        +++++      ",
"       +++++       ++6z/++     +++kzz+++     +++zz++       +++++       ",
"       ++++++      ++6z7+++    +++yzz+++     ++<zz++      ++++++       ",
"       +++}+++     ++6zz+++    +++zzz|++    +++czz++      ++)}++       ",
"       +++z+++     ++6zzb++    ++(zzzh++    +++zzz++     +++h+++       ",
"       +++mg+++    ++6zzq+++   ++ozzzh+++   ++bzzz++    +++bz+++       ",
"        ++9z^++    ++6zzz'++  +++pzzzs@++  ++@tzzz++    ++=zv+++       ",
"        ++6zv+++   ++6zzze++  ++$tzzzz#++  ++~zzzz++   +++nzb++        ",
"        ++3zzb+++  ++6zzzz@++ ++,yzzzz$++ +++hzzzz++  +++[zz1++        ",
"        ++)zzz$++  ++6zzzz0++ ++'zzzzz6++ ++#zzzzz++  ++$tzz1++        ",
"        +++zzzu+++ ++6zzzzk+++++1zzzzzy+++++bzzzzz++ +++nzzz(++        ",
"        +++zzzz4+++++6zzzzz+++++xzzzzzz+++++pzzzzz+++++^zzzz@++        ",
"         ++szzzz+++++6zzzzzu++++zzzzzzz)++++zzzzzz+++++xzzzz+++        ",
"         ++/zzzzn++++6zzzzzw$++>zzzzzzz|+++uzzzzzz++++bzzzzz++         ",
"         ++=zzzzz_+++6zzzvrp{++[lllllll_++*lnqrvzx+++)xzzzz2++         ",
"         ++=zzzzzz+++#===%#@+++++++++++++++++@#%=&+++(vzzzz+++         ",
"         ++@3|>++++++++++++++++++++++++++++++++++++++++++>5+++         ",
"         ++++++++++++$&====-^}2699mnnb973}(,====*%@+++++++++++         ",
"          +++++)clllpuxzzzzzzzzzzzzzzzzzzzzzzzzzyvqllli]++++++         ",
"          ++1zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzze+++         ",
"          +++qzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++          ",
"           ++&tzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzv%+++          ",
"           ++++tzzzzzzywurmllllllllllllllllllquwyzzzzzzs++++           ",
"            +++$zj/===*%$#+++++++++++++++++++@$%*==={ey^+++            ",
"             +++++++++++++++++++++++++++++++++++++++++++++             ",
"              +++++#*======(9fjmppqrrppnjga}-=====*#+++++              ",
"               +++nryzzzzzzzzzzzzzzzzzzzzzzzzzzzzzyso=+++              ",
"               +++jzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz+++               ",
"                ++6zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzw+++               ",
"               +++ozzj9}[[[[:/]{)'';,,)~]/_[[[[[8fxzz+++               ",
"               +++++++++++++++++++++++++++++++++++++++++               ",
"               ++++++++++++++++++++++++++++++++++++++++++              ",
"              ++++]1117enyzzzzzzzzzzzzzzzzzzzzqf9111/@+++              ",
"             +++2zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzr+++             ",
"             ++1zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz[++             ",
"            +++kzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz6++             ",
"            +++zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz1++             ",
"           +++0zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzn+++            ",
"           ++#zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz3++            ",
"            ++'szzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzw&++            ",
"            +++++++^300000ehjmqvyzzzzzywrmkifb00004:@++++++            ",
"             +++++++++++++++++++++++++++++++++++++++++++++             ",
"                +++++++++++++++++++++++++++++++++++++++                ",
"                                                                       ",
"                                                                       ",
"                                                                       ",
"                                                                       "};
